Effective_Mobile/Effective_Mobile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('myauth/', include('myauth.urls')),

    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name='schema'), name="redoc"),

]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

Effective_Mobile/myauth/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (LoginUser,
                    AboutMeView,
                    logout_view,
                    RegisterUser,
                    UsersListView,
                    UserDetail,
                    ProfileUpdate,
                    GroupViewSet,
                    UserViewSet,
                    SoftDeleteAccountView,

)


app_name = "myauth"

routers = DefaultRouter()
routers.register("groups", GroupViewSet)
routers.register("users", UserViewSet)

urlpatterns = [
    path("api/", include(routers.urls)),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path('register/', RegisterUser.as_view(), name='register'),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("users/", UsersListView.as_view(), name="users_list"),
    path("users/<int:pk>", UserDetail.as_view(), name="user_detail"),
    path("user/<int:pk>/update", ProfileUpdate.as_view(), name="profile_update"),
    path('delete-account/', SoftDeleteAccountView.as_view(), name='soft_delete_account'),

]

Effective_Mobile/myauth/models.py
from django.db import models
from django.contrib.auth.models import User


def avatar_image_directory_path(instance: "ProfileUser", filename: str):
    return f"profile/profile_{instance.pk}/avatar/{filename}"


class ProfileUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, verbose_name="Имя")
    surname = models.CharField(max_length=200, verbose_name="Фамилия")
    patronymic = models.CharField(max_length=200, verbose_name="Отчество")
    phone = models.CharField(max_length=15, verbose_name="Номер телефона")
    email = models.CharField(max_length=200, verbose_name="Email")
    avatar = models.ImageField(
        null=True,
        blank=True,
        upload_to=avatar_image_directory_path)

Effective_Mobile/myauth/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import ProfileUser


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class ProfileAvatarForm(forms.ModelForm):
    class Meta:
        model = ProfileUser
        fields = ('avatar',)


class ProfileUserForme(forms.ModelForm):
    class Meta:
        model = ProfileUser
        fields = ['name', 'surname', 'patronymic', 'phone', 'email']
        labels = {
            'name': 'Имя',
            'surname': 'Фамилия',
            'patronymic': 'Отчество',
            'phone': 'Номер телефона',
            'email': 'Email',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-input'}),
            'surname': forms.TextInput(attrs={'class': 'form-input'}),
            'patronymic': forms.TextInput(attrs={'class': 'form-input'}),
            'phone': forms.TextInput(attrs={'class': 'form-input'}),
        }


class NoForm(forms.Form):
    pass

Effective_Mobile/myauth/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User, Group
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpRequest
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from django.views.generic.edit import FormView
from rest_framework.viewsets import ModelViewSet


from .forms import RegisterUserForm, ProfileAvatarForm, ProfileUserForme, NoForm
from .models import ProfileUser
from .serializers import GroupSerializer, UserSerializer


class GroupViewSet(ModelViewSet):
    """
    Набор представлений для действий над Group.
    Полный CRUD для сущностей групп.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer


class UserViewSet(ModelViewSet):
    """
    Набор представлений для действий над User.
    Полный CRUD для сущностей user.
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer


class AboutMeView(LoginRequiredMixin, UpdateView):
    model = ProfileUser
    form_class = ProfileAvatarForm
    template_name_suffix = "_update_avatar_form"
    success_url = reverse_lazy("myauth:about-me")

    def get_object(self, queryset=None):
        print(f" текущий пользователь {self.request.user.profileuser.pk}\n {self.request.user}")
        print(f"object {ProfileUser.objects}")
        return self.request.user.profileuser


class LoginUser(LoginView):
    """
    Класс реализующий вход в систему
    """
    form_class = AuthenticationForm
    template_name = "myauth/login.html"
    redirect_authenticated_user = True


def logout_view(request: HttpRequest):
    logout(request)
    return redirect(reverse("myauth:login"))


class RegisterUser(CreateView):
    """
    Класс, реализующий регистрацию пользователя
    с вводом имени, фамилии, email, пароля, повтор пароля
    и вход в систему
    """
    form_class = RegisterUserForm
    template_name = 'myauth/register.html'
    success_url = reverse_lazy('myauth:about-me')

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        print(username)
        password = form.cleaned_data.get("password1")
        ProfileUser.objects.create(
            user=self.object,
            name=form.cleaned_data.get("first_name"),
            surname=form.cleaned_data.get("last_name"),
            email=form.cleaned_data.get("email"))

        user = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response


class UsersListView(LoginRequiredMixin, ListView):
    """
    Класс реализующий вывод списпа пользователей
    """
    template_name = "myauth/users_list.html"
    queryset = User.objects.select_related().all()
    context_object_name = "users"


class UserDetail(LoginRequiredMixin, DetailView):
    """
    Класс реализующий вывод информации о пользователе
    """
    template_name = "myauth/user_detail.html"
    queryset = User.objects.select_related().prefetch_related().all()
    context_object_name = "user"


class ProfileUpdate(UserPassesTestMixin, UpdateView):
    """
    Класс реализующий изменение информации о пользоаптеле
    """
    def test_func(self):
        return (self.request.user.is_superuser
                or self.request.user.pk == self.get_object().user.pk)

    model = ProfileUser
    template_name_suffix = "_update_form"
    form_class = ProfileUserForme

    def get_success_url(self):
        return reverse(
            "myauth:user_detail",
            kwargs={"pk": self.object.user.pk},
        )


class SoftDeleteAccountView(LoginRequiredMixin, FormView):
    """
    Класс реализующий мягкое удаление пользователя
    путем изменения is_active на False
    """
    template_name = 'myauth/soft_delete_account.html'
    success_url = reverse_lazy('myauth:login')
    form_class = NoForm

    def form_valid(self, form):
        user = self.request.user
        user.is_active = False
        user.save()

        logout(self.request)

        messages.success(self.request, 'Ваш аккаунт был деактивирован.')
        return super().form_valid(form)

Effective_Mobile/myauth/templates/myauth/about-me.html
{% extends "myauth/base.html" %}
[% load cache %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info About me</h1>
    {% if user.is_authenticated %}
        <h2>Пользователь {{ user.username |capfirst }}</h2>
        <p>User id: {{ user.pk }}</p>
        {% if user.profileuser %}
            {% if user.profileuser.avatar %}
                <img src="{{ user.profileuser.avatar.url }}" alt="{{ user.profileuser.avatar.name }}">
            {% else %}
                <div>No avatar</div>
            {% endif %}
            <p>Profile id: {{ user.profileuser.pk }}</p>
            <p>ФИО: {{ user.profileuser.surname }} {{ user.profileuser.name }} {{ user.profileuser.patronymic }}</p>
            <p>Жд</p>
            <p>Тел: {{ user.profileuser.phone }}</p>
            <p>E-mail: {{ user.profileuser.email }}</p>
        {% else %}
            <p>Имя: {{ user.first_name }}</p>
            <p>Фамилия: {{ user.last_name }}</p>
            <p>E-mail: {{ user.email }}</p>
        {% endif %}
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

Effective_Mobile/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Starting Myauth
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}


    <div>
        <p>
            <h3>Ссылки</h3>
                {% if user.is_authenticated %}
                    <a href="{% url 'myauth:about-me' %}">About-me</a><br>
                    <a href="{% url 'myauth:logout' %}">Log Out</a><br>
                    <a href="{% url 'myauth:users_list' %}">Список пользователей</a><br>
                    <h3>API</h3>
                        <a href="{% url 'swagger' %}">Swagger</a><br>
                        <a href="{% url 'redoc' %}">Redoc</a><br>
                        <a href="/myauth/api/users/">API пользователей</a><br>
                        <a href="/myauth/api/groups/">API групп</a><br>
                {% else %}
                    <a href="{% url 'myauth:login' %}">Вход</a> /
                    <a href="{% url 'myauth:register' %}">Регистрация</a><br>
                    <a href="/admin/">АДМИН панелька</a><br>
                {% endif %}
        </p>
    </div>
</body>
</html>

Effective_Mobile/myauth/templates/myauth/login.html
{% extends "myauth/base.html" %}

{% block title %}
    Login
{% endblock %}

{% block body %}

    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
{% endblock %}

Effective_Mobile/myauth/templates/myauth/profileuser_update_avatar_form.html
{% extends "myauth/base.html" %}
[% load cache %}

{% block title %}
    About me
{% endblock %}

{% block body %}
    <h1>User info About me</h1>
    {% if user.is_authenticated %}
        <h2>Пользователь {{ user.username |capfirst }}</h2>
        {% if request.user.pk == user.pk %}
            <br>
                <a href="{% url 'myauth:soft_delete_account' %}">Удалить аккаунт</a><br>
                <a href="{% url 'myauth:profile_update' pk=user.profileuser.pk %}">Обновить профиль</a>
        {% endif %}
        <p>User id: {{ user.pk }}</p>
        {% if user.profileuser %}
            {% if user.profileuser.avatar %}
                <img src="{{ user.profileuser.avatar.url }}" alt="{{ user.profileuser.avatar.name }}">
            {% else %}
                <div>No avatar</div>
            {% endif %}
            <p>Profile id: {{ user.profileuser.pk }}</p>
            <p>ФИО: {{ user.profileuser.surname }} {{ user.profileuser.name }} {{ user.profileuser.patronymic }}</p>
            <p>Тел: +7 {{ user.profileuser.phone }}</p>
            <p>E-mail: {{ user.profileuser.email }}</p>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Обновить аватар</button>
                </form>
        {% else %}
            <p>Имя: {{ user.first_name }}</p>
            <p>Фамилия: {{ user.last_name }}</p>
            <p>E-mail: {{ user.email }}</p>
        {% endif %}
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

Effective_Mobile/myauth/templates/myauth/profileuser_update_form.html
{% extends "myauth/base.html" %}

{% block title %}
    Update user
{% endblock %}

{% block body %}
    <h1>Update user</h1>
    {% if user.is_authenticated %}
        <div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>

        <div>
            <br>
            <a href="{% url 'myauth:about-me' %}">
                Обратно к пользователю {{ object.user.username |capfirst }}
            </a>
        </div>
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}
{% endblock %}

Effective_Mobile/myauth/templates/myauth/register.html
{% extends "myauth/base.html" %}

{% block title %}
    Register
{% endblock %}

{% block body %}
<h1>Регистрация</h1>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <!--<input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}-->
    <p ><button type="submit">Регистрация</button></p>
</form>
{% endblock %}

Effective_Mobile/myauth/templates/myauth/soft_delete_account.html
{% extends "myauth/base.html" %}

{% block title %}
    Delete Account
{% endblock %}

{% block body %}
    <h1>Подтверждение удаления аккаунта</h1>
    <p>Вы уверены, что хотите деактивировать свой аккаунт {{ user.username |capfirst }} ?</p>
    <p>Вы больше не сможете войти в него.</p>

    <div>
        <form method="post">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">Да, деактивировать</button>
        </form>
    </div>

    <div>
        <br>
            <a href="{% url 'myauth:about-me' %}">
                Обратно к пользователю {{ user.username |capfirst }}
            </a>
    </div>

{% endblock %}

Effective_Mobile/myauth/templates/myauth/user_detail.html
{% extends "myauth/base.html" %}

{% block title %}
  Users #{{ user.pk }}
{% endblock %}

{% block body %}
    <h1>Пользователь {{ user.username |capfirst }}</h1>
    {% if user.profileuser %}
        <table class="my-table">
            <thead>
                <th>User id: {{ user.pk }}</th>
                <th>Profile id: {{ user.profileuser.pk }}</th>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <p>Фамилия: {{ user.profileuser.surname }}</p>
                        <p>Имя: {{ user.profileuser.name }}</p>
                        <p>Отчество: {{ user.profileuser.patronymic }}</p>
                        <p>Тел: {{ user.profileuser.phone }}</p>
                        <p>E-mail: {{ user.profileuser.email }}</p>
                    </td>
                    <td>
                        {% if user.profileuser.avatar %}
                            <img src="{{ user.profileuser.avatar.url }}" alt="{{ user.profileuser.avatar.name }}">
                        {% else %}
                            <div>No avatar</div>
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
        {% if request.user.pk == user.pk or request.user.is_staff %}
            <br>
                <a href="{% url 'myauth:profile_update' pk=user.profileuser.pk %}">Обновить профиль</a>
        {% endif %}
    {% else %}
        <div>
            <p>Имя: {{ user.first_name }}</p>
            <p>Фамилия: {{ user.last_name }}</p>
            <p>E-mail: {{ user.email }}</p>
        </div>

        <div>
            <p>Доп информация отсутствует</p>
        </div>
    {% endif %}
{% endblock %}

Effective_Mobile/myauth/templates/myauth/users_list.html
{% extends "myauth/base.html" %}

{% block title %}
  Users list
{% endblock %}

{% block body %}
    <h1>Users:</h1>
        {% if user.is_authenticated %}
            {% if users %}
                <div>
                    {% for user in users %}

                        <div>
                            <p><a href="{% url 'myauth:user_detail' pk=user.pk %}"
                            >Пользователь: {{ user.username |capfirst }}</a></p>
                                {% if user.profileuser.avatar %}
                                    <a href="{% url 'myauth:user_detail' pk=user.pk %}"
                                    ><img src="{{ user.profileuser.avatar.url }}" alt="{{ user.profileuser.avatar.name }}"></a>
                                {% else %}
                                    <div>No avatar</div>
                                {% endif %}
                        </div>

                    {% endfor %}
                </div>

            {% else %}
                <h3>No users yet</h3>
            {% endif %}
        {% else %}
            <h2>User is anonymous</h2>
        {% endif %}
{% endblock %}